### ISSUE TITLE
Filter container by query string not work

### ISSUE THREAD

**Issue by yamete-devops** [pavanputhra/logspout-signoz#4]
I add container name filter but it still collect logs from all container

This is my compose
```yaml
  logspout-signoz:
    <<: *common
    image: "pavanputhra/logspout-signoz"
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SIGNOZ_LOG_ENDPOINT=http://otel-collector:8082
    command: signoz://otel-collector:8082?filter.name=my-proj-*
    depends_on:
      - otel-collector
```
